### ISSUE TITLE
Add support for C#-style extension methods

### ISSUE THREAD

**Issue by davidbyoung** [aphiria/aphiria#133]
We have a lot of decorator methods for things like HTTP requests and responses to make it easier to parse/format common data.  However, this requires an ugly syntax like:

```php
use Aphiria\Net\Http\Formatting\RequestParser;

$requestParser = new RequestParser();
$ip = $requestParser->getClientIPAddress($request);
```

It would be nice if we had the ability to dynamically register extension methods to give us a more fluent-looking syntax, eg

```php
$ip = $request->getClientIPAddress();
```

This would use a combination of `__call()`, a new `IExtendable` interface, and a trait.  We could then add some module components to let us set up these extension methods.

[PR](https://github.com/aphiria/aphiria/pull/134)

## Todo

- [x] Determine if it's possible to add this functionality to classes you do not "own", which is really the whole selling point of extension methods in other languages
   - I could add this functionality to Aphiria classes, but that doesn't open up the ability to call extension methods on 3rd party classes without implementing some base interface
   - If you have to manually call `ExtensionMethodRegistry::call()` in case the class you're extending doesn't implement `IExtendable`, does this library even get us much?
   - **Update:** It is correct that you cannot add this functionality to classes you do not own - really nothing will let you hook into a third party class in PHP at the moment.  So, this is really only valuable for code you own.
- [x] Add the ability to register extension methods via module components
- [x] Add baked-in extension methods for all parser/formatter Net library methods as well as any other decorator methods
- [x] Add some way of getting intellisense for baked-in extension methods, eg through PhpStorm meta files or PHPDoc
- [ ] Create the `extension-methods` GitHub repository prior to merging the PR 
- [ ] Add `aphiria/extension-methods` to Packagist

**Comment by davidbyoung** [comment]
I've ultimately decided that this is probably too much magic.  I'd love real extension methods in PHP, but the feedback from the community on this particular implementation was generally negative.  The biggest drawback with any hack to implement extension methods is that it requires a concrete class to implement an interface, which means you need to "own" the class you're extending.  Not saying that completely erases what extension methods can offer, but it just feels like there's not enough of an upside to offset the magic.
